### ISSUE TITLE
program check during Lisnum for test with a specific hex address 

### ISSUE THREAD

**Issue by BobBolch** [adesutherland/CMS-370-BREXX#63] opened 2021-01-30 13:51 UTC
Program check while processing a character string of hex digits of the form nnnEnnn, where each n is a numeric digit.

hextest                                                                                             
*** EBA9B6 PROG  000C ==> 005000                                                                    
B                                                                                                   
DMSITP143T EXPONENT OVERFLOW EXCEPTION OCCURRED AT EBA9B6 IN SYSTEM ROUTINE EXEC, RE-IPL CMS.       
CP ENTERED; DISABLED WAIT PSW '00020000 40F8B726'         

hextest exec:

               
                                
/* */                           
hexstr = '030E80'               
If hexstr = 'FFFFFF' then nop      
                                
Ready; T=0.01/0.01 08:39:03

**Comment by adesutherland** [comment] 2021-01-30 15:12
Wow! Just wow ...

**Comment by BobBolch** [comment] 2021-01-30 15:32
It's weird for sure!

It tries to convert the hex digits to 370 floating point by calling POS
as part of the check for whether the data is numeric. Of course, 030E80 has
the
form of a floating point number.

I ran into this while writing a REXX EXEC to convert addresses in the
GCCLIB/DMSREX memory into
entry point names and offsets from the BREXX TEXT and GCCLIB TEXT files, to
make it
easier for me to debug our stuff at the assembler level. My EXEC was
reading the CMS LOAD MAP files
to build the tables for the memory address lookup, when this came up.

As a bypass, I now do a  X2D for each address involved and manipulate the
addresses as decimal numbers.

/B

**Comment by adesutherland** [comment] 2021-03-11 20:45
Confirmed that this is trying to convert 030E80 to a float, the exception is caused because the exception is > 79 which is more than the VM/370 / IBM float format can handle.

I think the fix might be as simple as saying any exponent >79 is not a number - and leave it at that!!

**Comment by BobBolch** [comment] 2021-03-11 21:14
Should 030F80 or 030D80 be a number? Somehow, the context needs to
participate in the answer.

**Comment by adesutherland** [comment] 2021-03-11 21:25
Yeah - I agree two strings are two strings ....

**Comment by BobBolch** [comment] 2021-03-11 22:25
t hextest2 exec

/* */
trace ?A
hexstr = '030E72'
say hexstr
say hexstr + 1
hexstr = '030E73'
say hexstr
say hexstr + 1
hexstr = '030E74'
say hexstr
say hexstr + 1

Ready; T=0.01/0.01 22:15:15

hextest2

       +++ Interactive trace.  "Trace Off" to end debug.  ENTER to
continue. +++


     3 *-* hexstr = '030E72'



     4 *-* say hexstr

030E72



     5 *-* say hexstr + 1

3E+73



     6 *-* hexstr = '030E73'



     7 *-* say hexstr

030E73



     8 *-* say hexstr + 1

3E+74



     9 *-* hexstr = '030E74'



    10 *-* say hexstr

030E74



    11 *-* say hexstr + 1
                      3E+75

    12 *-*
Ready; T=0.02/0.03 22:16:22

Then if I try:
              hexstr = '030E75'

It program checks. Maybe an exponent check would handle this??

**************************************

  t hextest3 exec

/* */
trace ?A
hexstr = '001E75'
say hexstr
say hexstr + 1
hexstr = '002E75'
say hexstr
say hexstr + 1
hexstr = '005E75'
say hexstr
say hexstr + 1
hexstr = '006E75'
say hexstr
say hexstr + 1
hexstr = '007E75'
say hexstr
say hexstr + 1

Ready; T=0.01/0.01 22:22:38
hextest3

       +++ Interactive trace.  "Trace Off" to end debug.  ENTER to
continue. +++


     3 *-* hexstr = '001E75'



     4 *-* say hexstr

001E75



     5 *-* say hexstr + 1

1E+75



     6 *-* hexstr = '002E75'



     7 *-* say hexstr

002E75



     8 *-* say hexstr + 1

2E+75



     9 *-* hexstr = '005E75'



    10 *-* say hexstr

005E75



    11 *-* say hexstr + 1
                                             5E+75


    12 *-* hexstr = '006E75'

    13 *-* say hexstr
006E75

    14 *-* say hexstr + 1
6E+75

    15 *-* hexstr = '007E75'

    16 *-* say hexstr
007E75

    17 *-* say hexstr + 1
7E+75

    18 *-*
Ready; T=0.03/0.04 22:23:41

If I specify 008E75 it blows up, so testing the exponent alone will not be
enough.

/B

**Comment by BobBolch** [comment] 2021-03-11 22:36
I found the limits:

......representable numbers is from 16−65 to 1663 (approx. 5.39761 × 10−79
to 7.237005 × 1075)

**Comment by adesutherland** [comment] 2021-03-12 08:39
I can do a quick fix (limit the exponent to 75) and I am just checking why BREXX insists in converting strings to numbers when it is doing a comparison of two strings.

Longer term, Rather then just checking the exponent, is there anyway to trap the float overflow? An assembler demonstrator would be good if at all possible. Then this could drive the standards C Lib signal (SIGFPE) and we would have a way to detect the overflow in C and therefore in BREXX.

**Comment by BobBolch** [comment] 2021-03-12 09:38
I am surprised that there is no such handler already in the GCC runtime. I
can whip something up after the
Community Edition goes out. I would also like to understand why the heck
BREXX is converting things.

**Comment by adesutherland** [comment] 2021-03-13 17:55
Fixed in F0045

**Comment by BobBolch** [comment] 2021-03-13 20:32
Please remind me how to get to these F00xx fixes for testing.

Thanks /B

**Comment by mgrossmann** [comment] 2021-03-19 11:57
I did a short test with the latest VM/370 ## version.
Looks fine. 

I assume, that @BobBolch has already integrated fix F0045.

```
### CMS bREXX 0.9.12 Mar 15 2021 ###      
                                          
TYPE EXIT TO EXIT.                        
Ready(brexx);                             
hexstr = '030E80'                         
Ready(brexx);                             
If hexstr = 'FFFFFF' then nop             
Ready(brexx);  
```

/MIkeG

**Comment by BobBolch** [comment] 2021-03-19 12:06
Yes, The Community Edition has:
GCCLIB Version 0.8.5
BREXX Version 0.9.13

/Bob

**Comment by RossPatterson** [comment] 2024-09-24 14:51
Reading above, this appears to have been fixed and the fix was delivered in VM/370 CE.  Closing.

**Closed by RossPatterson** 2024-09-24 14:51 UTC
Labels: bug, Ready 4 Test
