### ISSUE TITLE
Trailing blanks removed from line retrieved from stack

### ISSUE THREAD

**Issue by BobBolch** [adesutherland/CMS-370-BREXX#50] opened 2020-11-30 16:23 UTC
REXX 'pull' statement is removing trailing blanks from stacked line.
After a push for a character constant with trailing blanks, the blanks are
present in the stacked line in CMS storage. Rexx pull calls @@RDTERM in 
CMSSYS ASSEMBLE and the trace shows that the length returned to 
the trailing null in the string is set after the trailing blanks. Displaying the
line retrieved by PULL shows that the trailing blanks have been removed.
IBM REXX on CMS preserves the blanks in the record.  

t test exec                                          
                                                     
/* */                                                
push 'ABCDEFG                                       '
pull line                                            
say ''''line''''                                     
                                                     
Ready; T=0.01/0.01 11:12:51                          
test                                                 
>EB8BB0 LH    4800100E E66562 CC=3                   
GPR  0 =  0000002E                                   
B                                                    
'ABCDEFG'                                            
Ready; T=0.02/0.03 11:13:23  

************************************
IBM REXX:

test2                                               
'ABCDEFG                                       '    
Ready; T=0.01/0.01 11:22:31

**Comment by adesutherland** [comment] 2020-12-02 16:00
I think that the problem is here is probably in GCCLIB. I seem to remember removing trailing blanks in some circumstances (although it should not be happening for STDIN / STACK)

**Comment by adesutherland** [comment] 2020-12-13 12:39
Fixed in F0033

**Comment by BobBolch** [comment] 2020-12-15 10:37
Fixed in F0033. Thank you.

**Closed** 2020-12-15 21:55 UTC
Labels: bug, resolved
